export const PATH = {
  HOME: '/',
  TIMETABLE: '/timetable',
  GRADE: '/grade',
  LIBRARY: '/library',
  LOST: '/lost',
  GRADUATION: '/graduation',
  FESTIVAL: '/festival',
  FOOD: '/food',
  SUGANG: '/sugang',
  GUIDE: '/guide',
  MY: '/my',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  RULES: '/rules',
} as const;
