name: "\U0001F528 Refactor"
description: "리팩터링을 해야할 부분이 있나요?"
labels: "\U0001F528 Refactor"
body:
  - type: textarea
    attributes:
      label: Describe
      description: 왜 리팩터링을 해야하는지 설명해주세요!
      placeholder: 자세히 적을수록 좋습니다.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tasks
      description: 리팩터링을 할 부분에 대해서 자세히 작성해 주세요!
      placeholder: 최대한 세분화 해서 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ETC
      description: 더 전달할 내용이 있다면 여기에 작성해주세요!
