export const ATOM_KEY = {
  IS_LOGGED_IN: 'isLoggedInState',
  MODAL: 'modalState',
  TOAST: 'toastState',
} as const;

export const QUERY_KEY = {
  MY_PROFILE: 'MyProfile',
  MY_BOARDS: 'MyBoards',
  MY_NOTIFICATIONS: 'MyNotifications',
  MY_COMMENTS: 'MyComments',
  MY_ACTIVITY: 'MyActivity',
  MY_BOOK: 'MyBook',
  BOARDS: 'Boards',
  BORDER_NOTICE: 'BorderNotice',
  BORDER_FREE: 'BorderFREE',
  BORDER_QNA: 'BorderQNA',
  BORDER_GRADUATED: 'BorderGraduated',
  ORGANIZATION: 'Organization',
  BOOK: 'Book',
  BOOK_DETAIL: 'BookDetail',
  BOOK_LOAN_RECORD: 'BookLoanRecord',
  BOOK_LOAN_RECORD_CONDITIONS: 'BookLoanRecordConditions',
  BOOK_LOAN_RECORD_OVERDUE: 'BookLoanRecordOverdue',
  NEWS: 'News',
  BLOG: 'Blog',
  HIRE: 'Hire',
  BIRTHDAY: 'Birthday',
  SCHEDULE: 'Schedule',
  SCHEDULE_COLLECT: 'ScheduleCollect',
  MAIN_ACTIVITY_PHOTO: 'MainActivityPhoto',
  COMMENTS: 'Comments',
  MEMBERSHIP_FEE: 'MembershipFee',
  UPLOADEDFILE: 'UploadedFile',
  SHARED_ACCOUNT: 'SharedAccount',
  SHARED_ACCOUNT_USAGE: 'SharedAccountUsage',
  ACTIVITY: 'Activity',
  ACTIVITY_BOARDS: 'ActivityBoards',
  ACTIVITY_GROUP_MY: 'ActivityGroupMy',
  ACTIVITY_GROUP_APPLY: 'ActivityGroupApply',
  ACTIVITY_BOARDS_MY_ASSIGNMENT: 'ActivityBoardsMyAssignment',
} as const;
