export const ATOM_KEY = {
  IS_LOGGED_IN: 'isLoggedInState',
  MODAL: 'modalState',
  TOAST: 'toastState',
};

export const QUERY_KEY = {
  MY_PROFILE: 'MyProfile',
  MY_BOARDS: 'MyBoards',
  MY_NOTIFICATIONS: 'MyNotifications',
  MY_COMMENTS: 'MyComments',
  MY_ACTIVITY: 'MyActivity',
  MY_BOOK_LIST: 'MyBookList',
  BORDER_NOTICE: 'BorderNotice',
  BORDER_FREE: 'BorderFREE',
  BORDER_QNA: 'BorderQNA',
  BORDER_GRADUATED: 'BorderGraduated',
  NEWS: 'News',
  BLOG: 'Blog',
  HIRE: 'Hire',
  BIRTHDAY: 'Birthday',
  SCHEDULE: 'Schedule',
  MAIN_ACTIVITY_PHOTO: 'MainActivityPhoto',
  COMMENTS: 'Comments',
  MEMBERSHIP_FEE: 'MembershipFee',
  UPLOADEDFILE: 'UploadedFile',
  ACTIVITY: 'Activity',
  ACTIVITY_BOARDS: 'ActivityBoards',
  ACTIVITY_BOARDS_MY_ASSIGNMENT: 'ActivityBoardsMyAssignment',
};
