export const PATH = {
  ROOT: '',
  MAIN: '/',
  MY: '/my',
  CALENDER: '/calendar',
  ACTIVITY: '/activity',
  COMMUNITY: '/community',
  COMMUNITY_DETAIL: '/community/:type',
  COMMUNITY_POST: '/community/:type/:id',
  COMMUNITY_NOTICE: '/community/notice',
  COMMUNITY_FREE: '/community/free',
  COMMUNITY_QNA: '/community/qna',
  COMMUNITY_GRADUATED: '/community/graduated',
  COMMUNITY_NEWS: '/community/news',
  COMMUNITY_HIRE: '/community/hire',
  COMMUNITY_WRITE: '/community/write',
  GROUP: '/group',
  GROUP_DETAIL: `/group/:id`,
  CREATE_GROUP: '/group/createGroup',
  GROUP_NOTICE: '/group/:id/notice',
  GROUP_STUDENT: '/group/:id/student',
  ASSIGNMENT_UPLOAD: '/group/:id/assignment/:assignmentId',
  NEWS: '/news',
  BLOG: '/blog',
  LIBRARY: '/library',
  SUPPORT: '/support',
  SITEMAP: '/sitemap',
};

export const PATH_FINDER = {
  NEWS_POST: (id: number) => `${PATH.NEWS}/${id}`,
  BLOG_POST: (id: number) => `${PATH.BLOG}/${id}`,
  COMMUNITY_POST: (sort: string, id: number) => `/community/${sort}/${id}`,
  GROUP_DETAIL: (id: number) => `${PATH.GROUP}/${id}`,
  GROUP_STUDENT: (id: number) => `${PATH.GROUP}/${id}/student`,
  GROUP_NOTICE: (id: number) => `${PATH.GROUP}/${id}/notice`,
  GROUP_ASSIGNMENT: (id: number, assignmentId: number) =>
    `${PATH.GROUP}/${id}/assignment/${assignmentId}`,
};
