export const ROUTE = {
  HOME: "/",
  COMMUNITY: "/community",
  COMMUNITY_NOTICE: "/community?tab=notice",
  COMMUNITY_FREE: "/community?tab=free",
  COMMUNITY_QUESTION: "/community?tab=question",
  COMMUNITY_INFORMATION: "/community?tab=information",
  COMMUNITY_WRITE: "/community/write",
  ACTIVITY: "/activity",
  ACTIVITY_STUDY: "/activity?tab=study",
  ACTIVITY_CREATE: "/activity/create",
  LIBRARY: "/library",
  LIBRARY_CREATE: "/library/create",
  MY: "/my",
  MY_POSTS: "/my/posts",
  MY_COMMENTS: "/my/comments",
  MY_LIBRARY: "/my/library",
  MY_ACTIVITY: "/my/activity",
};
